FROM python:3.9-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.5.0 \
    dbt-bigquery==1.5.0 \
    google-cloud-bigquery==3.13.0 \
    requests==2.31.0 \
    pandas==2.2.3

WORKDIR /opt/project

